services:
  db:
    image: postgres:18
    environment:
      POSTGRES_USER: dev
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: fatec-conecta
    ports:
      - "5432:5432"
    volumes:
      - ./.initdb:/docker-entrypoint-initdb.d

  # create-tables:
  #   build: ./create-tables-script
  #   depends_on:
  #     - db
  #   environment:
  #     DB_HOST: db
  #     DB_PORT: 5432
  #     DB_NAME: fatec-conecta
  #     DB_USER: dev
  #     DB_PASS: secret
  #   restart: "no"

  populate-tables:
    build: ./populate-tables-script
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: fatec-conecta
      DB_USER: dev
      DB_PASS: secret
    restart: "no"
